services:

  frontend:
    build: ./src/main/frontend-vue
    ports:
      - 5173:5173
    depends_on:
      - backend
    networks:
      - backend-postgres
      
  backend:
    build: .
    ports:
      - 8080:8080
    networks:
      - backend-postgres
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - postgres

  postgres:
    image: postgres:16.1-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
       POSTGRES_DB: ${POSTGRES_DB}
       POSTGRES_USER: ${POSTGRES_USER}
       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - backend-postgres

volumes:
  pgdata:
networks:
  backend-postgres: